In [36]:
import pandas as pd

df = pd.read_csv("/home/bs_thesis/Desktop/Rushi/BS_thesis/Survey on English Languages Diffculties in Telugu States.csv")


df = df.drop("Timestamp", axis=1)
df

,Age group,Gender,Medium of School,How difficult is it for you to understanding English conversation?\nఆంగ్ల సంభాషణను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?,"How difficult do you find it to speak English confidently while discussing passages or articles?\nప్యాసేజ్‌లు లేదా వ్యాసాల గురించి మాట్లాడేటప్పుడు, ఆత్మవిశ్వాసంతో ఇంగ్లీష్ మాట్లాడటం మీకు ఎంత కష్టం?",How difficult is it for you to write sentences in English?\nమీకు ఆంగ్లంలో వాక్యాలు రాయడం ఎంత కష్టం?,How difficult is it for you to read and understand English passages or articles?\nఇంగ్లీష్ పేరాగ్రాఫ్‌లు లేదా వ్యాసాలను చదివి అర్థం చేసుకోవడం మీకు ఎంత కష్టం?,How difficult is it for you to use English due to the influence of your mother tongue (Telugu)?\nమీ మాతృభాష (తెలుగు) ప్రభావం వల్ల మీకు ఇంగ్లీష్ ఉపయోగించడం ఎంత కష్టంగా ఉంటుంది?,How difficult is it for you to understand lectures in English?\nఇంగ్లీషులో ఉపన్యాసాలను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?,How difficult is it for you to watch English movies without subtitles?\nసబ్‌టైటిల్స్ లేకుండా ఇంగ్లీష్ సినిమాలు చూడటం మీకు ఎంత కష్టం?,"How difficult is it for you to watch English movies even with subtitles?\nసబ్‌టైటిల్స్‌తో చూసినప్పటికీ, మీకు ఇంగ్లీష్ సినిమాలు చూడటం ఎంత కష్టంగా ఉంటుంది?",How do you feel while learning English?\nఇంగ్లీష్ నేర్చుకునేటప్పుడు మీకు ఎలా అనిపిస్తుంది?,"As a Telugu medium student, how difficult was it for you to switch to an English-Medium Curriculum in higher studies?\nతెలుగు మాధ్యమంలో చదివిన విద్యార్థిగా, ఉన్నత విద్యలో ఆంగ్ల మాధ్యమ పాఠ్య ప్రణాళికకు మారడం మీకు ఎంత కష్టంగా అనిపించింది?",How difficult do you find it to work in other Indian states due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో పని చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?,How difficult do you find it to work in other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర దేశాలలో పనిచేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?,How difficult do you find it to study in other Indian states or other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో లేదా ఇతర దేశాలలో చదువుకోవడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?,How difficult do you find it to make friends who have different native languages?\nవేర్వేరు మాతృభాషలు ఉన్నవారితో స్నేహం చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?
0,15-19,Male,English medium,2,5,3,2,4,1,2,1,2,1,4,4,4,3
1,20-25,Female,English medium,2,3,1,2,3,1,3,1,1,1,2,3,2,2
2,20-25,Male,English medium,1,1,1,1,1,1,1,1,5,5,4,4,4,5
3,20-25,Male,English medium,1,4,1,1,3,1,2,1,2,1,4,4,4,3
4,20-25,Male,English medium,1,4,3,1,1,1,2,1,2,1,4,4,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,15-19,Female,Both,2,1,2,4,2,4,2,2,1,1,1,1,2,4
479,15-19,Female,English medium,2,3,1,2,1,2,3,4,3,2,4,5,5,3
480,15-19,Female,Both,3,4,2,2,3,2,4,2,1,2,4,2,3,1
481,15-19,Female,English medium,3,3,2,5,2,2,3,4,5,4,3,2,4,1
482,15-19,Female,English medium,3,2,1,3,2,4,4,4,4,3,3,3,3,4

In [37]:
df = df.rename(columns={
"How difficult is it for you to understanding English conversation?\nఆంగ్ల సంభాషణను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?":"Conv_diff",

"How difficult do you find it to speak English confidently while discussing passages or articles?\nప్యాసేజ్‌లు లేదా వ్యాసాల గురించి మాట్లాడేటప్పుడు, ఆత్మవిశ్వాసంతో ఇంగ్లీష్ మాట్లాడటం మీకు ఎంత కష్టం?":"Speak_diff",

"How difficult is it for you to write sentences in English?\nమీకు ఆంగ్లంలో వాక్యాలు రాయడం ఎంత కష్టం?": "Write_diff",

"How difficult is it for you to read and understand English passages or articles?\nఇంగ్లీష్ పేరాగ్రాఫ్‌లు లేదా వ్యాసాలను చదివి అర్థం చేసుకోవడం మీకు ఎంత కష్టం?":"Read_diff",

"How difficult is it for you to use English due to the influence of your mother tongue (Telugu)?\nమీ మాతృభాష (తెలుగు) ప్రభావం వల్ల మీకు ఇంగ్లీష్ ఉపయోగించడం ఎంత కష్టంగా ఉంటుంది?": "MT_influence",

"How difficult is it for you to understand lectures in English?\nఇంగ్లీషులో ఉపన్యాసాలను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?": "Lect_diff",

"How difficult is it for you to watch English movies without subtitles?\nసబ్‌టైటిల్స్ లేకుండా ఇంగ్లీష్ సినిమాలు చూడటం మీకు ఎంత కష్టం?": "Movie_Nosub",

"How difficult is it for you to watch English movies even with subtitles?\nసబ్‌టైటిల్స్‌తో చూసినప్పటికీ, మీకు ఇంగ్లీష్ సినిమాలు చూడటం ఎంత కష్టంగా ఉంటుంది?": "Movie_sub",

"How do you feel while learning English?\nఇంగ్లీష్ నేర్చుకునేటప్పుడు మీకు ఎలా అనిపిస్తుంది?":"Learning_feel",

"As a Telugu medium student, how difficult was it for you to switch to an English-Medium Curriculum in higher studies?\nతెలుగు మాధ్యమంలో చదివిన విద్యార్థిగా, ఉన్నత విద్యలో ఆంగ్ల మాధ్యమ పాఠ్య ప్రణాళికకు మారడం మీకు ఎంత కష్టంగా అనిపించింది?":"Switch_diff",

"How difficult do you find it to work in other Indian states due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో పని చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"work_india",

"How difficult do you find it to work in other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర దేశాలలో పనిచేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"Work_abroad",

"How difficult do you find it to study in other Indian states or other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో లేదా ఇతర దేశాలలో చదువుకోవడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"Study_other",

"How difficult do you find it to make friends who have different native languages?\nవేర్వేరు మాతృభాషలు ఉన్నవారితో స్నేహం చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"Friend_diff"})

In [38]:
df

,Age group,Gender,Medium of School,Conv_diff,Speak_diff,Write_diff,Read_diff,MT_influence,Lect_diff,Movie_Nosub,Movie_sub,Learning_feel,Switch_diff,work_india,Work_abroad,Study_other,Friend_diff
0,15-19,Male,English medium,2,5,3,2,4,1,2,1,2,1,4,4,4,3
1,20-25,Female,English medium,2,3,1,2,3,1,3,1,1,1,2,3,2,2
2,20-25,Male,English medium,1,1,1,1,1,1,1,1,5,5,4,4,4,5
3,20-25,Male,English medium,1,4,1,1,3,1,2,1,2,1,4,4,4,3
4,20-25,Male,English medium,1,4,3,1,1,1,2,1,2,1,4,4,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,15-19,Female,Both,2,1,2,4,2,4,2,2,1,1,1,1,2,4
479,15-19,Female,English medium,2,3,1,2,1,2,3,4,3,2,4,5,5,3
480,15-19,Female,Both,3,4,2,2,3,2,4,2,1,2,4,2,3,1
481,15-19,Female,English medium,3,3,2,5,2,2,3,4,5,4,3,2,4,1
482,15-19,Female,English medium,3,2,1,3,2,4,4,4,4,3,3,3,3,4

In [39]:
core_skills = [
    "Conv_diff",   
    "Speak_diff",
    "Write_diff",
    "Read_diff",
    "Lect_diff"
]

In [40]:
summary = df[core_skills].mean().sort_values(ascending=False)
print(summary)

Speak_diff    2.511387
Lect_diff     2.293996
Write_diff    2.175983
Read_diff     2.155280
Conv_diff     2.109731
dtype: float64

In [41]:
text_data = "The analysis of student difficulties in English language skills shows that "

for i, (col, val) in enumerate(summary.items()):
    skill = col.replace("_diff", "").capitalize()
    
    if i == 0:
        text_data += f"{skill} is the most difficult skill with an average score of {val:.2f}. "
    else:
        text_data += f"{skill} has an average difficulty score of {val:.2f}. "

print(text_data)

The analysis of student difficulties in English language skills shows that Speak is the most difficult skill with an average score of 2.51. Lect has an average difficulty score of 2.29. Write has an average difficulty score of 2.18. Read has an average difficulty score of 2.16. Conv has an average difficulty score of 2.11.

In [42]:
prompt = f"""
Analyze the following data:

{text_data}

1. Which skill is the most difficult?
2. Which skill is the least difficult?
3. Rank the skills from most to least difficult.
4. What overall learning pattern do you observe?
5. Do students struggle more with communication or comprehension skills?
6. What major challenges do students face?
7. What factors contribute to these difficulties?
8. Provide 2–3 key insights.
9. Identify any surprising trends.
10. What improvements would you suggest for students?
"""

In [ ]:
from groq import Groq
client = Groq(api_key="API KEY here")

chat = client.chat.completions.create(
    model="llama-3.1-8b-instant", 
    messages=[{"role": "user", "content": prompt}]
)

In [44]:
print(chat.choices[0].message.content)

Here's the analysis of the given data:

1. **Which skill is the most difficult?**
Based on the average scores, Speak (2.51) is the most difficult skill.

2. **Which skill is the least difficult?**
Based on the average scores, Read (2.16) is the least difficult skill.

3. **Rank the skills from most to least difficult.**
The skills, ranked from most difficult to least difficult, are:
- Speak (2.51)
- Lect (2.29)
- Write (2.18)
- Read (2.16)
- Conv (2.11)

4. **What overall learning pattern do you observe?**
There seems to be a general decreasing trend in difficulty scores from Speak to Read. This could indicate that students find reading skills to be relatively the easiest among the given options.

5. **Do students struggle more with communication or comprehension skills?**
Students appear to struggle more with communication skills (Speak and Lect) compared to comprehension skills (Read and Write). This could be an indication that English language skills in communication are a challenge for students.

6. **What major challenges do students face?**
The major challenges students face are likely related to English language skills, specifically in Speak and Lect. These skills could require more focus, attention, or practice for students to improve.

7. **What factors contribute to these difficulties?**
Possible factors contributing to these difficulties could be:
- Limited practice or exposure to English language use in real-life situations
- Inadequate instruction or support from teachers
- Individual differences in language learning ability
- Low motivation or interest in English language skills

8. **2–3 key insights.**
- Students have more difficulty with communication skills compared to comprehension skills.
- Overall, there's a pattern of decreasing difficulty from Speak to Read, indicating that students find reading more manageable.
- Possible areas of improvement include teaching more effective communication skills, providing sufficient practice opportunities, or offering individualized support to students.

9. **Surprising trends.**
There isn't a clear trend of surprise, but a noticeable point is the slight difference between Write (2.18) and Read (2.16). It's possible that writing skills have become marginally more difficult for students compared to reading skills.

10. **What improvements would you suggest for students?**
For students, improvements could include:
- More practice with English language use in Speak and Lect, either in class or through self-study
- Focusing on developing conversation and presentation skills through regular exercises or role-playing activities
- Regular reading habits or language exchange programs to enhance reading skills and comprehension

In [ ]:
from groq import Groq
client = Groq(api_key="API_key_here")

chat = client.chat.completions.create(
    model="llama-3.3-70b-versatile", 
    messages=[{"role": "user", "content": prompt}]
)

In [46]:
print(chat.choices[0].message.content)

Based on the provided data, here's a comprehensive analysis:

1. **Most difficult skill**: The most difficult skill is Speak, with an average score of 2.51.

2. **Least difficult skill**: The least difficult skill is Conv (Conversation), with an average score of 2.11.

3. **Ranking of skills from most to least difficult**:
   - Speak (2.51)
   - Lect (Lecture, 2.29)
   - Write (2.18)
   - Read (2.16)
   - Conv (2.11)

4. **Overall learning pattern**: The overall learning pattern suggests that students struggle more with skills that require active production or interaction, such as speaking and lecturing, compared to receptive skills like reading. However, the differences in difficulty are relatively small, indicating a generally balanced challenge across all skills.

5. **Communication vs. comprehension skills**: Students seem to struggle more with communication skills (Speak, Lect, and Conv) than with comprehension skills (Read). This is evident from the higher average difficulty scores for Speak and Lect compared to Read.

6. **Major challenges**: Students face significant challenges with speaking skills, indicating potential difficulties with fluency, pronunciation, or expressing thoughts in English.

7. **Contributing factors**: The difficulties could be attributed to various factors, including lack of practice, insufficient exposure to the language, cultural or linguistic barriers, or inadequate instruction. However, without more specific data, it's challenging to pinpoint the exact factors.

8. **Key insights**:
   - Speaking is the most challenging skill for students, suggesting a need for more speaking practice or interactive activities.
   - There is a slight leaning towards communication skills being more difficult, which could indicate a need for more emphasis on these areas in instruction.
   - The scores are relatively close, suggesting that students face a balanced set of challenges across different skills.

9. **Surprising trends**: One surprising trend could be the relatively low difficulty score for Conv (Conversation), which is often considered a challenging skill due to its spontaneous nature. This could indicate that, despite the overall struggle with speaking, students might be more accustomed to or comfortable with conversational interactions than with more formal speaking tasks like lectures.

10. **Suggestions for improvements**:
    - **Enhanced speaking practice**: Incorporate more speaking activities, discussions, and presentations into the curriculum to help students improve their speaking skills.
    - **Interactive learning**: Use interactive tools, role-plays, and group work to make learning more engaging and to provide opportunities for students to practice their communication skills in a supportive environment.
    - **Personalized feedback**: Offer regular, personalized feedback on pronunciation, fluency, and content to help students address their specific weaknesses in speaking and other skills.

summarize whole the dataset(14 questions)

In [47]:
skills = [
    "Conv_diff",   
    "Speak_diff",
    "Write_diff",
    "Read_diff",
    "Lect_diff",
    "MT_influence",
    "Movie_Nosub",
    "Movie_sub",
    "Learning_feel",
    "Switch_diff",
    "work_india",
    "Work_abroad",
    "Study_other",
    "Friend_diff"
]

In [48]:
summary = df[skills].mean().sort_values(ascending=False)
print(summary)

Work_abroad      2.790890
work_india       2.737060
Study_other      2.714286
Movie_Nosub      2.703934
Learning_feel    2.616977
Switch_diff      2.577640
Friend_diff      2.523810
Speak_diff       2.511387
MT_influence     2.434783
Movie_sub        2.358178
Lect_diff        2.293996
Write_diff       2.175983
Read_diff        2.155280
Conv_diff        2.109731
dtype: float64

In [49]:
text_data = "The analysis of student difficulties in English language skills shows that "

for i, (col, val) in enumerate(summary.items()):
    skill = col.replace("_diff", "").capitalize()
    
    if i == 0:
        text_data += f"{skill} is the most difficult skill with an average score of {val:.2f}. "
    else:
        text_data += f"{skill} has an average difficulty score of {val:.2f}. "

print(text_data)

The analysis of student difficulties in English language skills shows that Work_abroad is the most difficult skill with an average score of 2.79. Work_india has an average difficulty score of 2.74. Study_other has an average difficulty score of 2.71. Movie_nosub has an average difficulty score of 2.70. Learning_feel has an average difficulty score of 2.62. Switch has an average difficulty score of 2.58. Friend has an average difficulty score of 2.52. Speak has an average difficulty score of 2.51. Mt_influence has an average difficulty score of 2.43. Movie_sub has an average difficulty score of 2.36. Lect has an average difficulty score of 2.29. Write has an average difficulty score of 2.18. Read has an average difficulty score of 2.16. Conv has an average difficulty score of 2.11.

In [50]:
prompt = f"""
Analyze the following data:

{text_data}

1. Which skill is the most difficult?
2. Which skill is the least difficult?
3. Rank the skills from most to least difficult.
4. What overall learning pattern do you observe?
5. Do students struggle more with communication or comprehension skills?
6. What major challenges do students face?
7. What factors contribute to these difficulties?
8. Provide 2–3 key insights.
9. Identify any surprising trends.
10. What improvements would you suggest for students?
"""

In [ ]:
from groq import Groq
client = Groq(api_key="API_KEY_HERE")

chat = client.chat.completions.create(
    model="llama-3.1-8b-instant", 
    messages=[{"role": "user", "content": prompt}]
)

In [52]:
print(chat.choices[0].message.content)

Based on the provided data, I can answer the questions and provide analysis as follows:

1. The most difficult skill is Work_abroad with an average difficulty score of 2.79.

2. The least difficult skill is Write with an average difficulty score of 2.18, along with Read, which also has a difficulty score of 2.16. Write and Read are tied for the least difficult, but Write is the actual least due to its lower score compared to being tied.

3. Here's the ranking from most to least difficult:

   - Work_abroad: 2.79
   - Work_india: 2.74
   - Study_other: 2.71
   - Movie_nosub: 2.70
   - Learning_feel: 2.62
   - Switch: 2.58
   - Friend: 2.52
   - Speak: 2.51
   - Mt_influence: 2.43
   - Movie_sub: 2.36
   - Lect: 2.29
   - Write: 2.18
   - Read: 2.16
   - Conv: 2.11

4. The overall learning pattern shows that students struggle the most with skills related to professional or formal interactions, followed by skills that require understanding and engaging with different types of media (e.g., sub/snosub), then personal relationships (e.g., Friend), and finally comprehension and writing skills.

5. Based on the ranking, students seem to struggle more with comprehension skills (e.g., Movie_nosub, Conv) than communication skills (e.g., Speak, Friend).

6. Major challenges for students include difficulties with professional interactions (e.g., Work_abroad, Work_india), understanding and engaging with different types of media (e.g., Movie_nosub, Movie_sub), personal relationships (e.g., Friend), and comprehension and writing skills (e.g., Write, Read).

7. Factors contributing to these difficulties could be the students' unfamiliarity with professional settings, limited exposure to various media platforms, or weak literacy and comprehension skills.

8. Key insights:
   - Students face significant challenges with skills related to professional interactions and formal communication.
   - A strong correlation exists between skills that involve media (e.g., sub/snosub) and difficulty levels.
   - Writing and comprehension skills are also major concerns for students.

9. Surprising trends:
   - The relatively low difficulty score of Mt_influence compared to other skills that might be perceived as more challenging (e.g., Write).
   - The presence of multiple skills with low difficulty scores (e.g., Read, Conv), suggesting some ease in comprehension and writing tasks.

10. Improvements suggested for students:

    - Focus on developing skills for professional interactions (e.g., Work_abroad, Work_india) and formal communication (e.g., Lect, Conv).
    - Engage in various media platforms and forms of content to improve understanding and engagement with sub/snosub materials.
    - Strengthen literacy and comprehension skills through practice and review of writing and reading tasks.
    - Seek additional resources, training, or support to address specific areas of difficulty and improve overall language proficiency.

In [ ]:
from groq import Groq
client = Groq(api_key="API KEY HERE")

chat = client.chat.completions.create(
    model="llama-3.3-70b-versatile", 
    messages=[{"role": "user", "content": prompt}]
)

In [54]:
print(chat.choices[0].message.content)

Based on the provided data, here are the answers to the questions:

1. **The most difficult skill is Work_abroad with an average difficulty score of 2.79.**

2. **The least difficult skill is Conv (Conversation) with an average difficulty score of 2.11.**

3. **The skills ranked from most to least difficult are:**
   - Work_abroad (2.79)
   - Work_india (2.74)
   - Study_other (2.71)
   - Movie_nosub (2.70)
   - Learning_feel (2.62)
   - Switch (2.58)
   - Friend (2.52)
   - Speak (2.51)
   - Mt_influence (2.43)
   - Movie_sub (2.36)
   - Lect (2.29)
   - Write (2.18)
   - Read (2.16)
   - Conv (2.11)

4. **The overall learning pattern observed is that students tend to struggle more with skills that involve practical application or real-life scenarios (e.g., Work_abroad, Work_india, Study_other) compared to more basic skills like reading and writing.**

5. **Students seem to struggle more with communication skills (e.g., Work_abroad, Speak, Switch, Friend) than comprehension skills (e.g., Read, Lect, Movie_sub).**

6. **Major challenges faced by students include adapting to real-life situations, communicating effectively, and navigating different contexts (e.g., working abroad or in India).**

7. **Factors contributing to these difficulties may include lack of exposure to real-life scenarios, inadequate practice in communication skills, and insufficient feedback or guidance.**

8. **Key insights:**
   - Students need more practice and exposure to real-life situations to improve their English language skills.
   - Communication skills are a significant area of difficulty for students.
   - Basic skills like reading and writing are relatively less challenging for students.

9. **Surprising trends:**
   - The fact that Work_india is more difficult than Study_other, despite both being related to professional or academic contexts, suggests that students may struggle more with cultural or regional nuances in India.
   - The relatively low difficulty score for Movie_sub (watching movies with subtitles) compared to Movie_nosub (watching movies without subtitles) implies that subtitles can be a helpful tool for improving comprehension.

10. **Improvement suggestions for students:**
    - Engage in more real-life conversations and practice communicating in different contexts.
    - Seek feedback from teachers, peers, or language exchange partners to improve communication skills.
    - Watch English movies or TV shows without subtitles to improve listening comprehension.
    - Read English books, articles, or news regularly to improve reading comprehension.
    - Practice writing in English through journals, blogs, or social media to improve writing skills.